/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness probe; carries no dependencies so it succeeds even before Spotify auth.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Me
     * @description Return the authenticated Spotify user's id and display name.
     */
    get: operations['me_api_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Playlists
     * @description List the user's playlists with load/cache state, Liked Songs first.
     *
     *     ``track_count`` stays None for Liked Songs until a refresh job loads it — Spotify's saved-tracks endpoint offers no cheap count without fetching pages.
     */
    get: operations['list_playlists_api_playlists_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Playlist
     * @description Start (or join) a background job that fetches the playlist and builds its dataset.
     *
     *     Cache-warm loads also run as jobs — they finish in seconds and keep the client's flow uniform. A queued or running job for the same playlist is joined,
     *     not duplicated.
     */
    post: operations['refresh_playlist_api_playlists__playlist_id__refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/tracks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Playlist Tracks
     * @description Return the flattened track rows of a loaded playlist.
     *
     *     Raises:
     *         DatasetNotLoadedError: Mapped to HTTP 409 when no refresh job has loaded the playlist yet.
     */
    get: operations['playlist_tracks_api_playlists__playlist_id__tracks_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/labels': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Labels
     * @description Tag/genre frequency bars — the primary rule-helper chart (bar click → tag filter).
     */
    get: operations['labels_api_playlists__playlist_id__insights_labels_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/years': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Years
     * @description Tracks per release year, pre-binned server-side so a bar click/box-select maps to exact years.
     */
    get: operations['years_api_playlists__playlist_id__insights_years_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/additions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Additions
     * @description Library growth: additions per period plus cumulative tracks/hours.
     */
    get: operations['additions_api_playlists__playlist_id__insights_additions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/discovery': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Discovery
     * @description Artist discovery waves: how many artists enter the library for the first time per period.
     */
    get: operations['discovery_api_playlists__playlist_id__insights_discovery_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/seasonal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Seasonal
     * @description Additions by calendar month aggregated across years (always 12 rows).
     */
    get: operations['seasonal_api_playlists__playlist_id__insights_seasonal_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/artists': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Artists
     * @description Track counts per credited artist; repeatable ``genre`` params implement the cascading genre→artist re-scope.
     */
    get: operations['artists_api_playlists__playlist_id__insights_artists_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/insights/release-vs-added': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Release Vs Added
     * @description Release-year vs added-year scatter rows; carries track ids so a lasso selection can become a playlist.
     */
    get: operations['release_vs_added_api_playlists__playlist_id__insights_release_vs_added_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/organizer/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Preview
     * @description Dry-run the spec against the loaded playlist: bucket contents and stats, nothing written anywhere.
     *
     *     Raises:
     *         DatasetNotLoadedError: Mapped to 409 when the playlist has no loaded dataset.
     *         ValueError: Mapped to 400 for invalid specs (inverted bounds, duplicate bucket names, ...).
     */
    post: operations['preview_api_organizer_preview_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/organizer/apply': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Apply
     * @description Materialize chosen buckets as NEW playlists under a named batch (background job).
     *
     *     Validation happens before the job starts so spec errors surface synchronously; the job then re-runs the pure assignment and performs the
     *     only writes in the API: create playlist + add tracks per non-empty bucket. Empty buckets are skipped and reported.
     *
     *     Raises:
     *         DatasetNotLoadedError: Mapped to 409 when the playlist has no loaded dataset.
     *         ValueError: Mapped to 400 for invalid specs or bucket_names not present in the spec.
     */
    post: operations['apply_api_organizer_apply_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/organizer/batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Batches
     * @description The local history of Apply batches, newest first.
     */
    get: operations['batches_api_organizer_batches_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job
     * @description Return the current snapshot of a background job.
     *
     *     Raises:
     *         NotFoundError: Mapped to HTTP 404 when the job id is unknown or already evicted.
     */
    get: operations['get_job_api_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AdditionRow
     * @description One period of the library-growth chart.
     */
    AdditionRow: {
      /**
       * Period
       * Format: date-time
       */
      period: string
      /** Added */
      added: number
      /** Cumulative Tracks */
      cumulative_tracks: number
      /** Cumulative Hours */
      cumulative_hours: number
    }
    /**
     * AdditionsResponse
     * @description Response of ``GET .../insights/additions``.
     */
    AdditionsResponse: {
      /** Freq */
      freq: string
      /** Rows */
      rows: components['schemas']['AdditionRow'][]
    }
    /**
     * ApplyRequest
     * @description Body of ``POST /api/organizer/apply``: which buckets of the spec to materialize, under which batch name.
     */
    ApplyRequest: {
      /** Playlist Id */
      playlist_id: string
      spec: components['schemas']['OrganizerSpecIn']
      /** Bucket Names */
      bucket_names: string[]
      /**
       * Include Rest
       * @default false
       */
      include_rest: boolean
      /**
       * Rest Name
       * @default Rest
       */
      rest_name: string
      /**
       * Public
       * @default false
       */
      public: boolean
      /** Batch Name */
      batch_name: string
    }
    /**
     * ArtistCountRow
     * @description One bar of the (optionally genre-scoped) artist chart.
     */
    ArtistCountRow: {
      /** Artist Id */
      artist_id: string
      /** Artist Name */
      artist_name: string
      /** Track Count */
      track_count: number
    }
    /**
     * ArtistRuleIn
     * @description Boundary mirror of ``organizer.ArtistRule``: match any credited artist.
     */
    ArtistRuleIn: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'artist'
      /** Artist Ids */
      artist_ids: string[]
    }
    /**
     * ArtistsResponse
     * @description Response of ``GET .../insights/artists``; ``scoped_to_genres`` echoes the cascading genre filter.
     */
    ArtistsResponse: {
      /** Scoped To Genres */
      scoped_to_genres: string[]
      /** Rows */
      rows: components['schemas']['ArtistCountRow'][]
    }
    /**
     * BatchOut
     * @description One recorded Apply batch.
     */
    BatchOut: {
      /** Batch Name */
      batch_name: string
      /** Created At */
      created_at: string
      /** Source Playlist Id */
      source_playlist_id: string
      /** Created */
      created: components['schemas']['CreatedPlaylistOut'][]
    }
    /**
     * BatchesResponse
     * @description Response of ``GET /api/organizer/batches``, newest first.
     */
    BatchesResponse: {
      /** Batches */
      batches: components['schemas']['BatchOut'][]
    }
    /**
     * BucketPreview
     * @description One bucket's dry-run result.
     */
    BucketPreview: {
      /** Name */
      name: string
      /** Count */
      count: number
      /** Duration Ms Total */
      duration_ms_total: number
      /** Track Ids */
      track_ids: string[]
    }
    /**
     * BucketSpecIn
     * @description One named bucket; rules AND together.
     */
    BucketSpecIn: {
      /** Name */
      name: string
      /** Rules */
      rules?: components['schemas']['RuleIn'][]
    }
    /**
     * CreatedPlaylistOut
     * @description One playlist created by an Apply.
     */
    CreatedPlaylistOut: {
      /** Bucket Name */
      bucket_name: string
      /** Playlist Id */
      playlist_id: string
      /** Url */
      url: string
      /** Added */
      added: number
    }
    /**
     * DiscoveryResponse
     * @description Response of ``GET .../insights/discovery``.
     */
    DiscoveryResponse: {
      /** Freq */
      freq: string
      /** Rows */
      rows: components['schemas']['DiscoveryRow'][]
    }
    /**
     * DiscoveryRow
     * @description One period of the artist-discovery-waves chart.
     */
    DiscoveryRow: {
      /**
       * Period
       * Format: date-time
       */
      period: string
      /** New Artists */
      new_artists: number
    }
    /**
     * DurationRuleIn
     * @description Boundary mirror of ``organizer.DurationRule`` (whole seconds).
     */
    DurationRuleIn: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'duration'
      /** Min Seconds */
      min_seconds?: number | null
      /** Max Seconds */
      max_seconds?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Liveness probe body.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
    }
    /**
     * JobAccepted
     * @description 202 response carrying the id to poll at ``GET /api/jobs/{job_id}``.
     */
    JobAccepted: {
      /** Job Id */
      job_id: string
    }
    /**
     * JobErrorOut
     * @description Error block of a failed job.
     */
    JobErrorOut: {
      /** Code */
      code: string
      /** Message */
      message: string
    }
    /**
     * JobOut
     * @description Response of ``GET /api/jobs/{job_id}``.
     */
    JobOut: {
      /** Id */
      id: string
      /** Kind */
      kind: string
      status: components['schemas']['JobStatus']
      progress: components['schemas']['JobProgressOut']
      /** Result */
      result: {
        [key: string]: unknown
      } | null
      error: components['schemas']['JobErrorOut'] | null
    }
    /**
     * JobProgressOut
     * @description Progress block of a job snapshot.
     */
    JobProgressOut: {
      /** Phase */
      phase: string
      /** Done */
      done: number
      /** Total */
      total: number | null
      /** Message */
      message: string
    }
    /**
     * JobStatus
     * @description Lifecycle states of a background job.
     * @enum {string}
     */
    JobStatus: 'queued' | 'running' | 'done' | 'error'
    /**
     * LabelCountRow
     * @description One bar of the tag/genre frequency chart.
     */
    LabelCountRow: {
      /** Label */
      label: string
      /** Count */
      count: number
    }
    /**
     * LabelsResponse
     * @description Response of ``GET .../insights/labels``; ``field`` echoes which label column was counted.
     */
    LabelsResponse: {
      /**
       * Field
       * @enum {string}
       */
      field: 'genres' | 'tags'
      /** Rows */
      rows: components['schemas']['LabelCountRow'][]
    }
    /**
     * MeResponse
     * @description The authenticated Spotify user.
     */
    MeResponse: {
      /** Id */
      id: string
      /** Display Name */
      display_name: string
    }
    /**
     * OrganizerSpecIn
     * @description The organizer configuration as sent by the frontend.
     */
    OrganizerSpecIn: {
      /** Buckets */
      buckets?: components['schemas']['BucketSpecIn'][]
      /**
       * Allow Duplicates
       * @default true
       */
      allow_duplicates: boolean
    }
    /**
     * OverlapOut
     * @description Tracks shared by two buckets.
     */
    OverlapOut: {
      /** Bucket A */
      bucket_a: string
      /** Bucket B */
      bucket_b: string
      /** Count */
      count: number
    }
    /**
     * PlaylistItem
     * @description One sidebar entry; id ``__liked__`` is the synthetic Liked Songs pseudo-playlist.
     *
     *     ``track_count`` is None when unknown (Liked Songs before its first load). ``cached_at`` is the raw-response cache write time, or None when uncached/stale.
     */
    PlaylistItem: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Owner Name */
      owner_name: string
      /** Track Count */
      track_count: number | null
      /** Public */
      public: boolean
      /** Is Liked */
      is_liked: boolean
      /** Loaded */
      loaded: boolean
      /** Cached At */
      cached_at: string | null
    }
    /**
     * PlaylistsResponse
     * @description Response of ``GET /api/playlists``.
     */
    PlaylistsResponse: {
      /** Items */
      items: components['schemas']['PlaylistItem'][]
    }
    /**
     * PreviewRequest
     * @description Body of ``POST /api/organizer/preview``.
     */
    PreviewRequest: {
      /** Playlist Id */
      playlist_id: string
      spec: components['schemas']['OrganizerSpecIn']
    }
    /**
     * PreviewResponse
     * @description Response of ``POST /api/organizer/preview`` — a pure dry-run, nothing written.
     */
    PreviewResponse: {
      /** Buckets */
      buckets: components['schemas']['BucketPreview'][]
      /** Rest Track Ids */
      rest_track_ids: string[]
      /** Rest Count */
      rest_count: number
      stats: components['schemas']['PreviewStats']
    }
    /**
     * PreviewStats
     * @description Aggregate dry-run numbers.
     */
    PreviewStats: {
      /** Coverage Pct */
      coverage_pct: number
      /** Duplicate Count */
      duplicate_count: number
      /** Overlaps */
      overlaps: components['schemas']['OverlapOut'][]
      /** Skipped Local Count */
      skipped_local_count: number
    }
    /**
     * RefreshRequest
     * @description Body of ``POST /api/playlists/{id}/refresh``; ``force`` bypasses the response cache.
     */
    RefreshRequest: {
      /**
       * Force
       * @default false
       */
      force: boolean
    }
    /**
     * ReleaseVsAddedResponse
     * @description Response of ``GET .../insights/release-vs-added``.
     */
    ReleaseVsAddedResponse: {
      /** Rows */
      rows: components['schemas']['ReleaseVsAddedRow'][]
    }
    /**
     * ReleaseVsAddedRow
     * @description One dot of the release-vs-added scatter; ``track_id`` is None for local files (excluded from lasso selections).
     */
    ReleaseVsAddedRow: {
      /** Track Id */
      track_id: string | null
      /** Release Year */
      release_year: number
      /** Added Year */
      added_year: number
      /** Track */
      track: string
      /** Artist */
      artist: string
    }
    RuleIn:
      | components['schemas']['TagRuleIn']
      | components['schemas']['YearRuleIn']
      | components['schemas']['DurationRuleIn']
      | components['schemas']['ArtistRuleIn']
      | components['schemas']['TrackRuleIn']
    /**
     * SeasonalResponse
     * @description Response of ``GET .../insights/seasonal``.
     */
    SeasonalResponse: {
      /** Rows */
      rows: components['schemas']['SeasonalRow'][]
    }
    /**
     * SeasonalRow
     * @description One calendar month of the seasonal-profile chart (always 12 rows).
     */
    SeasonalRow: {
      /** Month */
      month: number
      /** Month Name */
      month_name: string
      /** Added */
      added: number
    }
    /**
     * TagRuleIn
     * @description Boundary mirror of ``organizer.TagRule``: match any of the labels (case-insensitive) in the chosen field.
     */
    TagRuleIn: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'tag'
      /** Labels */
      labels: string[]
      /**
       * Field
       * @default genres
       * @enum {string}
       */
      field: 'genres' | 'tags'
    }
    /**
     * TrackRow
     * @description One flattened track, mirroring the columns of ``PlaylistAnalyzer.from_playlist``'s DataFrame.
     */
    TrackRow: {
      /** Track Id */
      track_id: string | null
      /** Name */
      name: string
      /** Primary Artist Id */
      primary_artist_id: string | null
      /** Primary Artist Name */
      primary_artist_name: string
      /** Artist Ids */
      artist_ids: string[]
      /** Artist Names */
      artist_names: string[]
      /** Album Name */
      album_name: string
      /** Release Year */
      release_year: number | null
      /** Duration Ms */
      duration_ms: number
      /** Explicit */
      explicit: boolean
      /** Added At */
      added_at: string | null
      /** Is Local */
      is_local: boolean
      /** Tags */
      tags: string[]
      /** Genres */
      genres: string[]
    }
    /**
     * TrackRuleIn
     * @description Boundary mirror of ``organizer.TrackRule``: an explicit track-id set (the lasso selection).
     */
    TrackRuleIn: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'track'
      /** Track Ids */
      track_ids: string[]
    }
    /**
     * TracksResponse
     * @description Response of ``GET /api/playlists/{id}/tracks``.
     */
    TracksResponse: {
      /** Playlist Id */
      playlist_id: string
      /** Name */
      name: string
      /** Tracks */
      tracks: components['schemas']['TrackRow'][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * YearCountRow
     * @description One pre-binned bar of the release-year chart (clicks map to exact years).
     */
    YearCountRow: {
      /** Year */
      year: number
      /** Count */
      count: number
    }
    /**
     * YearRuleIn
     * @description Boundary mirror of ``organizer.YearRule``; bound validation happens in the core dataclass.
     */
    YearRuleIn: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'year'
      /** Min Year */
      min_year?: number | null
      /** Max Year */
      max_year?: number | null
    }
    /**
     * YearsResponse
     * @description Response of ``GET .../insights/years``.
     */
    YearsResponse: {
      /** Rows */
      rows: components['schemas']['YearCountRow'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  me_api_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
    }
  }
  list_playlists_api_playlists_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlaylistsResponse']
        }
      }
    }
  }
  refresh_playlist_api_playlists__playlist_id__refresh_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  playlist_tracks_api_playlists__playlist_id__tracks_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TracksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  labels_api_playlists__playlist_id__insights_labels_get: {
    parameters: {
      query?: {
        field?: 'genres' | 'tags'
        top_n?: number
      }
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LabelsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  years_api_playlists__playlist_id__insights_years_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['YearsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  additions_api_playlists__playlist_id__insights_additions_get: {
    parameters: {
      query?: {
        freq?: 'W' | 'M' | 'Q' | 'Y'
      }
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdditionsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  discovery_api_playlists__playlist_id__insights_discovery_get: {
    parameters: {
      query?: {
        freq?: 'W' | 'M' | 'Q' | 'Y'
      }
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DiscoveryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  seasonal_api_playlists__playlist_id__insights_seasonal_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SeasonalResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  artists_api_playlists__playlist_id__insights_artists_get: {
    parameters: {
      query?: {
        genre?: string[] | null
        top_n?: number
      }
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ArtistsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  release_vs_added_api_playlists__playlist_id__insights_release_vs_added_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReleaseVsAddedResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  preview_api_organizer_preview_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PreviewRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PreviewResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  apply_api_organizer_apply_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApplyRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  batches_api_organizer_batches_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchesResponse']
        }
      }
    }
  }
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
