/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness probe; carries no dependencies so it succeeds even before Spotify auth.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Me
     * @description Return the authenticated Spotify user's id and display name.
     */
    get: operations['me_api_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Playlists
     * @description List the user's playlists with load/cache state, Liked Songs first.
     *
     *     ``track_count`` stays None for Liked Songs until a refresh job loads it — Spotify's saved-tracks endpoint offers no cheap count without fetching pages.
     */
    get: operations['list_playlists_api_playlists_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Playlist
     * @description Start (or join) a background job that fetches the playlist and builds its dataset.
     *
     *     Cache-warm loads also run as jobs — they finish in seconds and keep the client's flow uniform. A queued or running job for the same playlist is joined,
     *     not duplicated.
     */
    post: operations['refresh_playlist_api_playlists__playlist_id__refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/playlists/{playlist_id}/tracks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Playlist Tracks
     * @description Return the flattened track rows of a loaded playlist.
     *
     *     Raises:
     *         DatasetNotLoadedError: Mapped to HTTP 409 when no refresh job has loaded the playlist yet.
     */
    get: operations['playlist_tracks_api_playlists__playlist_id__tracks_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job
     * @description Return the current snapshot of a background job.
     *
     *     Raises:
     *         NotFoundError: Mapped to HTTP 404 when the job id is unknown or already evicted.
     */
    get: operations['get_job_api_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Liveness probe body.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
    }
    /**
     * JobAccepted
     * @description 202 response carrying the id to poll at ``GET /api/jobs/{job_id}``.
     */
    JobAccepted: {
      /** Job Id */
      job_id: string
    }
    /**
     * JobErrorOut
     * @description Error block of a failed job.
     */
    JobErrorOut: {
      /** Code */
      code: string
      /** Message */
      message: string
    }
    /**
     * JobOut
     * @description Response of ``GET /api/jobs/{job_id}``.
     */
    JobOut: {
      /** Id */
      id: string
      /** Kind */
      kind: string
      status: components['schemas']['JobStatus']
      progress: components['schemas']['JobProgressOut']
      /** Result */
      result: {
        [key: string]: unknown
      } | null
      error: components['schemas']['JobErrorOut'] | null
    }
    /**
     * JobProgressOut
     * @description Progress block of a job snapshot.
     */
    JobProgressOut: {
      /** Phase */
      phase: string
      /** Done */
      done: number
      /** Total */
      total: number | null
      /** Message */
      message: string
    }
    /**
     * JobStatus
     * @description Lifecycle states of a background job.
     * @enum {string}
     */
    JobStatus: 'queued' | 'running' | 'done' | 'error'
    /**
     * MeResponse
     * @description The authenticated Spotify user.
     */
    MeResponse: {
      /** Id */
      id: string
      /** Display Name */
      display_name: string
    }
    /**
     * PlaylistItem
     * @description One sidebar entry; id ``__liked__`` is the synthetic Liked Songs pseudo-playlist.
     *
     *     ``track_count`` is None when unknown (Liked Songs before its first load). ``cached_at`` is the raw-response cache write time, or None when uncached/stale.
     */
    PlaylistItem: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Owner Name */
      owner_name: string
      /** Track Count */
      track_count: number | null
      /** Public */
      public: boolean
      /** Is Liked */
      is_liked: boolean
      /** Loaded */
      loaded: boolean
      /** Cached At */
      cached_at: string | null
    }
    /**
     * PlaylistsResponse
     * @description Response of ``GET /api/playlists``.
     */
    PlaylistsResponse: {
      /** Items */
      items: components['schemas']['PlaylistItem'][]
    }
    /**
     * RefreshRequest
     * @description Body of ``POST /api/playlists/{id}/refresh``; ``force`` bypasses the response cache.
     */
    RefreshRequest: {
      /**
       * Force
       * @default false
       */
      force: boolean
    }
    /**
     * TrackRow
     * @description One flattened track, mirroring the columns of ``PlaylistAnalyzer.from_playlist``'s DataFrame.
     */
    TrackRow: {
      /** Track Id */
      track_id: string | null
      /** Name */
      name: string
      /** Primary Artist Id */
      primary_artist_id: string | null
      /** Primary Artist Name */
      primary_artist_name: string
      /** Artist Ids */
      artist_ids: string[]
      /** Artist Names */
      artist_names: string[]
      /** Album Name */
      album_name: string
      /** Release Year */
      release_year: number | null
      /** Duration Ms */
      duration_ms: number
      /** Explicit */
      explicit: boolean
      /** Added At */
      added_at: string | null
      /** Is Local */
      is_local: boolean
      /** Tags */
      tags: string[]
      /** Genres */
      genres: string[]
    }
    /**
     * TracksResponse
     * @description Response of ``GET /api/playlists/{id}/tracks``.
     */
    TracksResponse: {
      /** Playlist Id */
      playlist_id: string
      /** Name */
      name: string
      /** Tracks */
      tracks: components['schemas']['TrackRow'][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  me_api_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
    }
  }
  list_playlists_api_playlists_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlaylistsResponse']
        }
      }
    }
  }
  refresh_playlist_api_playlists__playlist_id__refresh_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  playlist_tracks_api_playlists__playlist_id__tracks_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        playlist_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TracksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
